pipeline {
    agent any

    environment {
        IMAGE_NAME = "my-python-app"
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                echo "📥 Cloning repository..."
                git url: 'https://github.com/daraye-tech/day-1.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                echo "🔧 Setting up Python virtual environment and installing dependencies..."
                dir('my-app') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Build docker image') {
            steps {
                echo "🔧 Building Docker image"
                dir('my-app') {
                    sh '''
                        docker build -t $IMAGE_NAME:$IMAGE_TAG .
                        docker image ls
                    '''
                }
            }
        }
        stage('Test') {
            steps {
                echo "✅ Running unit tests..."
                dir('my-app') {
                    sh '''
                        . venv/bin/activate
                        pytest test.py
                    '''
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "🚀 Deployment step (placeholder)..."
                sh 'echo "Deployed!"'
            }
        }
    }
}

