pipeline {
    agent any

    environment {
    IMAGE_NAME = "node-app"
    IMAGE_TAG = "build-${BUILD_NUMBER}"
    }

    stages {
        stage('Build') {
            steps {
                echo "🔧 Installing dependencies..."
                dir('node-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build docker image') {
            steps {
                echo "🐳 Building Docker image..."
                dir('node-app') {
                    withEnv(["IMAGE_NAME=${IMAGE_NAME}", "IMAGE_TAG=${IMAGE_TAG}"]) {
                        sh '''
                            docker build -t $IMAGE_NAME:$IMAGE_TAG .
                            docker image ls
                        '''
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo "✅ Running unit tests..."
        }

        stage('Deliver') {
            steps {
                echo "🚀 Deployment step (placeholder)..."
                sh 'echo "Deployed!"'
            }
        }

        stage('Clean Up') {
            steps {
                echo "🧹 Cleaning up unused Docker images..."
                sh 'docker image prune -f'
            }
        }
    }

    post {
        success {
            echo '✅ Build and deployment successful!'
        }
        failure {
            echo '❌ Build failed. Check the logs.'
        }
    }
}
